//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo
    {
        public int IdAmigo { get; set; }
        public int IdJugador1 { get; set; }
        public int IdJugador2 { get; set; }
    
        public virtual Jugador Jugador1 { get; set; }
        public virtual Jugador Jugador2 { get; set; }
    }
}
