//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigo
    {
        public string NombreJugadorA { get; set; }
        public string NombreJugadorB { get; set; }
    
        public virtual Jugador JugadorA { get; set; }
        public virtual Jugador JugadorB { get; set; }
    }
}
