//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amistad
    {
        public int IdJugadorA { get; set; }
        public int IdJugadorB { get; set; }
    
        public virtual Jugador JugadorA { get; set; }
        public virtual Jugador JugadorB { get; set; }
    }
}
