//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    
    public enum EstadoSolicitudAmistad : int
    {
        Pendiente = 0,
        Aceptada = 1,
        Rechazada = 2
    }
}
