//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesRompecabezasFei : DbContext
    {
        public EntidadesRompecabezasFei()
            : base("name=EntidadesRompecabezasFei")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<SolicitudAmistad> SolicitudAmistad { get; set; }
        public virtual DbSet<Amistad> Amistad { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<ResultadoPartida> ResultadoPartida { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
    }
}
