//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesRompecabezasFei : DbContext
    {
        public EntidadesRompecabezasFei()
            : base("name=EntidadesRompecabezasFei")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Jugador> Jugador { get; set; }
        public virtual DbSet<SolicitudAmistad> SolicitudAmistad { get; set; }
        public virtual DbSet<Amistad> Amistad { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<ResultadoPartida> ResultadoPartida { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
    }
}
