//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IdPartida { get; set; }
        public int Dificultad { get; set; }
        public int IdSala { get; set; }
    
        public virtual Sala Sala { get; set; }
    }
}
