//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sala()
        {
            this.MinimoJugadores = "2";
        }
    
        public int IdSala { get; set; }
        public string Codigo { get; set; }
        public int MaximoJugadores { get; set; }
        public string MinimoJugadores { get; set; }
        public Nullable<int> IdAnfitrion { get; set; }
    
        public virtual Jugador Anfitrion { get; set; }
    }
}
