//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public int IdSala { get; set; }
        public int Codigo { get; set; }
        public short MaximoJugadores { get; set; }
        public short MinimoJugadores { get; set; }
        public int IdAnfitrion { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
