//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAmistad
    {
        public int Estado { get; set; }
        public string FechaEnvioSolicitud { get; set; }
        public int IdJugadorOrigen { get; set; }
        public int IdJugadorDestino { get; set; }
    
        public virtual Jugador JugadorOrigen { get; set; }
        public virtual Jugador JugadorDestino { get; set; }
    }
}
