//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RompecabezasFei.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RompecabezasFei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cambiar avatar.
        /// </summary>
        public static string BOTON_ACTUALIZACIONINFORMACION_CAMBIARAVATAR {
            get {
                return ResourceManager.GetString("BOTON_ACTUALIZACIONINFORMACION_CAMBIARAVATAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activada.
        /// </summary>
        public static string BOTON_AJUSTES_ACTIVADA {
            get {
                return ResourceManager.GetString("BOTON_AJUSTES_ACTIVADA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desactivada.
        /// </summary>
        public static string BOTON_AJUSTES_DESACTIVADA {
            get {
                return ResourceManager.GetString("BOTON_AJUSTES_DESACTIVADA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string BOTON_AMIGOS_AGREGAR {
            get {
                return ResourceManager.GetString("BOTON_AMIGOS_AGREGAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enviar solicitud.
        /// </summary>
        public static string BOTON_AMIGOS_ENVIARSOLICITUD {
            get {
                return ResourceManager.GetString("BOTON_AMIGOS_ENVIARSOLICITUD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        public static string BOTON_AMIGOS_RECHAZAR {
            get {
                return ResourceManager.GetString("BOTON_AMIGOS_RECHAZAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string BOTON_AMIGOS_REMOVER {
            get {
                return ResourceManager.GetString("BOTON_AMIGOS_REMOVER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Solicitudes.
        /// </summary>
        public static string BOTON_AMIGOS_SOLICITUDES {
            get {
                return ResourceManager.GetString("BOTON_AMIGOS_SOLICITUDES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de restablecimiento inválido.
        /// </summary>
        public static string BOTON_CODIGO_INVALIDO {
            get {
                return ResourceManager.GetString("BOTON_CODIGO_INVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reenviar código.
        /// </summary>
        public static string BOTON_CONFIRMACIONCORREO_REENVIARCODIGO {
            get {
                return ResourceManager.GetString("BOTON_CONFIRMACIONCORREO_REENVIARCODIGO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actualizar información.
        /// </summary>
        public static string BOTON_INFORMACIONJUGADOR_ACTUALIZARINFORMACION {
            get {
                return ResourceManager.GetString("BOTON_INFORMACIONJUGADOR_ACTUALIZARINFORMACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        public static string BOTON_INFORMACIONJUGADOR_CAMBIARCONTRASENA {
            get {
                return ResourceManager.GetString("BOTON_INFORMACIONJUGADOR_CAMBIARCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string BOTON_INICIOSESION_INICIARSESION {
            get {
                return ResourceManager.GetString("BOTON_INICIOSESION_INICIARSESION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modo invitado.
        /// </summary>
        public static string BOTON_INICIOSESION_INVITADO {
            get {
                return ResourceManager.GetString("BOTON_INICIOSESION_INVITADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Crear nueva sala.
        /// </summary>
        public static string BOTON_MENUPRINCIPAL_CREACIONSALA {
            get {
                return ResourceManager.GetString("BOTON_MENUPRINCIPAL_CREACIONSALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unirse a sala.
        /// </summary>
        public static string BOTON_MENUPRINCIPAL_UNIRSESALA {
            get {
                return ResourceManager.GetString("BOTON_MENUPRINCIPAL_UNIRSESALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ajustes de partida.
        /// </summary>
        public static string BOTON_OPCIONESSALA_AJUSTESPARTIDA {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_AJUSTESPARTIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Convertir en anfitrión.
        /// </summary>
        public static string BOTON_OPCIONESSALA_CONVERTIRANFITRION {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_CONVERTIRANFITRION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Difícil.
        /// </summary>
        public static string BOTON_OPCIONESSALA_DIFICIL {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_DIFICIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expulsar.
        /// </summary>
        public static string BOTON_OPCIONESSALA_EXPULSAR {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_EXPULSAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fácil.
        /// </summary>
        public static string BOTON_OPCIONESSALA_FACIL {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_FACIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitar amigo.
        /// </summary>
        public static string BOTON_OPCIONESSALA_INVITACIONAMIGO {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_INVITACIONAMIGO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitar por correo.
        /// </summary>
        public static string BOTON_OPCIONESSALA_INVITACIONCORREO {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_INVITACIONCORREO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitar a sala.
        /// </summary>
        public static string BOTON_OPCIONESSALA_INVITACIONSALA {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_INVITACIONSALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string BOTON_OPCIONESSALA_MEDIA {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_MEDIA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minutos.
        /// </summary>
        public static string BOTON_OPCIONESSALA_MINUTOS {
            get {
                return ResourceManager.GetString("BOTON_OPCIONESSALA_MINUTOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abandonar partida.
        /// </summary>
        public static string BOTON_PARTIDA_ABANDONOPARTIDA {
            get {
                return ResourceManager.GetString("BOTON_PARTIDA_ABANDONOPARTIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actualizar contraseña.
        /// </summary>
        public static string BOTON_RESTABLECIMIENTOCONTRASENA_ACTUALIZARCONTRASENA {
            get {
                return ResourceManager.GetString("BOTON_RESTABLECIMIENTOCONTRASENA_ACTUALIZARCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string BOTON_SALA_ENVIARMENSAJE {
            get {
                return ResourceManager.GetString("BOTON_SALA_ENVIARMENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Iniciar partida.
        /// </summary>
        public static string BOTON_SALA_INICIARPARTIDA {
            get {
                return ResourceManager.GetString("BOTON_SALA_INICIARPARTIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opciones sala.
        /// </summary>
        public static string BOTON_SALA_OPCIONESSALA {
            get {
                return ResourceManager.GetString("BOTON_SALA_OPCIONESSALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unirse.
        /// </summary>
        public static string BOTON_UNIRSESALA_UNIRSE {
            get {
                return ResourceManager.GetString("BOTON_UNIRSESALA_UNIRSE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string COLUMNA_AJUSTES_IDIOMAESPANOL {
            get {
                return ResourceManager.GetString("COLUMNA_AJUSTES_IDIOMAESPANOL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        public static string COLUMNA_AJUSTES_IDIOMAINGLES {
            get {
                return ResourceManager.GetString("COLUMNA_AJUSTES_IDIOMAINGLES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres abandonar la partida?.
        /// </summary>
        public static string ETIQUETA_ABANDONOPARTIDA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_ABANDONOPARTIDA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación de abandono de partida.
        /// </summary>
        public static string ETIQUETA_ABANDONOPARTIDA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_ABANDONOPARTIDA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres abandonar la sala?.
        /// </summary>
        public static string ETIQUETA_ABANDONOSALA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_ABANDONOSALA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación de abandono de sala.
        /// </summary>
        public static string ETIQUETA_ABANDONOSALA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_ABANDONOSALA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONCONTRASENA_CONTRASENAACTUAL {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONCONTRASENA_CONTRASENAACTUAL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actualizar información.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONINFORMACION {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONINFORMACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La actualización de la información no se ha realizado.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONNOREALIZADA {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONNOREALIZADA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La actualización de la información se ha realizado correctamente.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONREALIZADA {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_ACTUALIZACIONREALIZADA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar información.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_ERRORACTUALIZACION {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_ERRORACTUALIZACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Actualización realizada correctamente.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_MENSAJEACTUALIZACION {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_MENSAJEACTUALIZACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no se encuentra disponible.
        /// </summary>
        public static string ETIQUETA_ACTUALIZACIONINFORMACION_NOMBRENODISPONIBLE {
            get {
                return ResourceManager.GetString("ETIQUETA_ACTUALIZACIONINFORMACION_NOMBRENODISPONIBLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string ETIQUETA_AJUSTES_IDIOMA {
            get {
                return ResourceManager.GetString("ETIQUETA_AJUSTES_IDIOMA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Música.
        /// </summary>
        public static string ETIQUETA_AJUSTES_MUSICA {
            get {
                return ResourceManager.GetString("ETIQUETA_AJUSTES_MUSICA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desconectado.
        /// </summary>
        public static string ETIQUETA_AMIGOS_DESCONECTADO {
            get {
                return ResourceManager.GetString("ETIQUETA_AMIGOS_DESCONECTADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to En partida.
        /// </summary>
        public static string ETIQUETA_AMIGOS_ENPARTIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_AMIGOS_ENPARTIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para mandar una solicitud de amistad a un jugador, debes de ingresar su nombre de usuario.
        /// </summary>
        public static string ETIQUETA_AMIGOS_INSTRUCCIONSOLICITUDAMISTAD {
            get {
                return ResourceManager.GetString("ETIQUETA_AMIGOS_INSTRUCCIONSOLICITUDAMISTAD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string ETIQUETA_AMIGOS_USUARIONOENCONTRADO {
            get {
                return ResourceManager.GetString("ETIQUETA_AMIGOS_USUARIONOENCONTRADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Si regresas, el proceso de actualización de información se cancelará ¿Estás seguro de que deseas regresar?.
        /// </summary>
        public static string ETIQUETA_CANCELACIONACTUALIZACIONINFO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONACTUALIZACIONINFO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación cancelación actualización de información.
        /// </summary>
        public static string ETIQUETA_CANCELACIONACTUALIZACIONINFO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONACTUALIZACIONINFO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que desea cancelar el proceso de registro? La información ingresada se descartará.
        /// </summary>
        public static string ETIQUETA_CANCELACIONREGISTRO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONREGISTRO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación cancelación registro de jugador.
        /// </summary>
        public static string ETIQUETA_CANCELACIONREGISTRO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONREGISTRO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Si regresas, el proceso de restablecimiento de contraseña se cancelará ¿Estás seguro de que desea regresar?.
        /// </summary>
        public static string ETIQUETA_CANCELACIONRESTABLECIMIENTO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONRESTABLECIMIENTO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación cancelación restablecimiento contraseña.
        /// </summary>
        public static string ETIQUETA_CANCELACIONRESTABLECIMIENTO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CANCELACIONRESTABLECIMIENTO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres cerrar la sesión?.
        /// </summary>
        public static string ETIQUETA_CERRARSESION_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CERRARSESION_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación de cerrar sesión.
        /// </summary>
        public static string ETIQUETA_CERRARSESION_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CERRARSESION_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Codigo no coincide.
        /// </summary>
        public static string ETIQUETA_CODIGO_CODIGONOCOINCIDE {
            get {
                return ResourceManager.GetString("ETIQUETA_CODIGO_CODIGONOCOINCIDE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código de restablecimiento de contraseña.
        /// </summary>
        public static string ETIQUETA_CODIGO_CODIGORESTABLECIMIENTO {
            get {
                return ResourceManager.GetString("ETIQUETA_CODIGO_CODIGORESTABLECIMIENTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Revisa tu bandeja de entrada e introduce el código de restablecimiento de contraseña que te hemos enviado.
        /// </summary>
        public static string ETIQUETA_CODIGO_INSTRUCCIONCODIGO {
            get {
                return ResourceManager.GetString("ETIQUETA_CODIGO_INSTRUCCIONCODIGO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Introduce el código.
        /// </summary>
        public static string ETIQUETA_CODIGO_INTRODUCECODIGO {
            get {
                return ResourceManager.GetString("ETIQUETA_CODIGO_INTRODUCECODIGO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El codigo ingresado no coincide.
        /// </summary>
        public static string ETIQUETA_CODIGO_MENSAJECODIGONOCOINCIDE {
            get {
                return ResourceManager.GetString("ETIQUETA_CODIGO_MENSAJECODIGONOCOINCIDE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código de confirmación.
        /// </summary>
        public static string ETIQUETA_CONFIRMACIONCORREO_CODIGOCONFIRMACION {
            get {
                return ResourceManager.GetString("ETIQUETA_CONFIRMACIONCORREO_CODIGOCONFIRMACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación de correo electrónico.
        /// </summary>
        public static string ETIQUETA_CONFIRMACIONCORREO_CONFIRMACIONCORREO {
            get {
                return ResourceManager.GetString("ETIQUETA_CONFIRMACIONCORREO_CONFIRMACIONCORREO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para completar tu registro, te enviamos un código a tu correo electrónico, ingresalo a continuación.
        /// </summary>
        public static string ETIQUETA_CONFIRMACIONCORREO_INSTRUCCIONCORREO {
            get {
                return ResourceManager.GetString("ETIQUETA_CONFIRMACIONCORREO_INSTRUCCIONCORREO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminar.
        /// </summary>
        public static string ETIQUETA_CONFIRMACIONCORREO_TERMINAR {
            get {
                return ResourceManager.GetString("ETIQUETA_CONFIRMACIONCORREO_TERMINAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña se ha actualizado correctamente.
        /// </summary>
        public static string ETIQUETA_CONTRASENAACTUALIZADA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CONTRASENAACTUALIZADA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña actualizada.
        /// </summary>
        public static string ETIQUETA_CONTRASENAACTUALIZADA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CONTRASENAACTUALIZADA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres convertir al jugador en anfitrión?.
        /// </summary>
        public static string ETIQUETA_CONVERTIRANFITRION_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_CONVERTIRANFITRION_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación de convertir jugador en anfitrión.
        /// </summary>
        public static string ETIQUETA_CONVERTIRANFITRION_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_CONVERTIRANFITRION_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro de que quieres eliminar al jugador de tu lista de amigos?.
        /// </summary>
        public static string ETIQUETA_ELIMINACIONAMIGO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_ELIMINACIONAMIGO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación eliminación amigo.
        /// </summary>
        public static string ETIQUETA_ELIMINACIONAMIGO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_ELIMINACIONAMIGO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión con la base de datos. Por favor, inténtelo más tarde..
        /// </summary>
        public static string ETIQUETA_ERRORCONEXIONBASEDEDATOS_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_ERRORCONEXIONBASEDEDATOS_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error de conexión base de datos.
        /// </summary>
        public static string ETIQUETA_ERRORCONEXIONBASEDEDATOS_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_ERRORCONEXIONBASEDEDATOS_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer una conexión con el servidor. Por favor, inténtelo más tarde..
        /// </summary>
        public static string ETIQUETA_ERRORCONEXIONSERVIDOR_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_ERRORCONEXIONSERVIDOR_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error de conexión con el servidor.
        /// </summary>
        public static string ETIQUETA_ERRORCONEXIONSERVIDOR_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_ERRORCONEXIONSERVIDOR_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que quieres expulsar al jugador?.
        /// </summary>
        public static string ETIQUETA_EXPULSIONJUGADOR_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_EXPULSIONJUGADOR_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmación expulsión de jugador.
        /// </summary>
        public static string ETIQUETA_EXPULSIONJUGADOR_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_EXPULSIONJUGADOR_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string ETIQUETA_GENERAL_ACEPTAR {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_ACEPTAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actualizar contraseña.
        /// </summary>
        public static string ETIQUETA_GENERAL_ACTUALIZACIONCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_ACTUALIZACIONCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        public static string ETIQUETA_GENERAL_AJUSTES {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_AJUSTES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string ETIQUETA_GENERAL_AMIGOS {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_AMIGOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string ETIQUETA_GENERAL_CANCELAR {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CANCELAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de sala.
        /// </summary>
        public static string ETIQUETA_GENERAL_CODIGOSALA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CODIGOSALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmar nueva contraseña.
        /// </summary>
        public static string ETIQUETA_GENERAL_CONFIRMACIONCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CONFIRMACIONCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string ETIQUETA_GENERAL_CONFIRMAR {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CONFIRMAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string ETIQUETA_GENERAL_CONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida.
        /// </summary>
        public static string ETIQUETA_GENERAL_CONTRASENAINVALIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CONTRASENAINVALIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string ETIQUETA_GENERAL_CORREO {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_CORREO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to En línea.
        /// </summary>
        public static string ETIQUETA_GENERAL_ENLINEA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_ENLINEA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guardar cambios.
        /// </summary>
        public static string ETIQUETA_GENERAL_GUARDARCAMBIOS {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_GUARDARCAMBIOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitado.
        /// </summary>
        public static string ETIQUETA_GENERAL_INVITADO {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_INVITADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        public static string ETIQUETA_GENERAL_JUGADORES {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_JUGADORES", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Alguno de los campos está vacío.
        /// </summary>
        public static string ETIQUETA_GENERAL_MENSAJECAMPOSVACIOS {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_MENSAJECAMPOSVACIOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de jugador.
        /// </summary>
        public static string ETIQUETA_GENERAL_NOMBREJUGADOR {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_NOMBREJUGADOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña.
        /// </summary>
        public static string ETIQUETA_GENERAL_NUEVACONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_NUEVACONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe ser de al menos 8 caracteres, debes incluir letras mayúsculas, minúsculas y números.
        /// </summary>
        public static string ETIQUETA_GENERAL_REQUISITOSCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_REQUISITOSCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rompecabezas FEI.
        /// </summary>
        public static string ETIQUETA_GENERAL_ROMPECABEZASFEI {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_ROMPECABEZASFEI", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string ETIQUETA_GENERAL_SIGUIENTE {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_SIGUIENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuario existente.
        /// </summary>
        public static string ETIQUETA_GENERAL_USUARIOEXISTENTE {
            get {
                return ResourceManager.GetString("ETIQUETA_GENERAL_USUARIOEXISTENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La información se ha actualizado correctamente.
        /// </summary>
        public static string ETIQUETA_INFORMACIONACTUALIZADA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_INFORMACIONACTUALIZADA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Información actualizada.
        /// </summary>
        public static string ETIQUETA_INFORMACIONACTUALIZADA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_INFORMACIONACTUALIZADA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Partidas ganadas.
        /// </summary>
        public static string ETIQUETA_INFORMACIONJUGADOR_PARTIDASGANADAS {
            get {
                return ResourceManager.GetString("ETIQUETA_INFORMACIONJUGADOR_PARTIDASGANADAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Partidas jugadas.
        /// </summary>
        public static string ETIQUETA_INFORMACIONJUGADOR_PARTIDASJUGADAS {
            get {
                return ResourceManager.GetString("ETIQUETA_INFORMACIONJUGADOR_PARTIDASJUGADAS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_CONTRASENAINCORRECTA {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_CONTRASENAINCORRECTA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión cancelado.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_INICIOSESIONCANCELADO {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_INICIOSESIONCANCELADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar sesión.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_MENSAJEINICIOSESIONERROR {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_MENSAJEINICIOSESIONERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_RECUPERACIONCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_RECUPERACIONCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes una cuenta? Registrate aquí.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_REGISTRO {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_REGISTRO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuario incorrecto.
        /// </summary>
        public static string ETIQUETA_INICIOSESION_USUARIOINCORRECTO {
            get {
                return ResourceManager.GetString("ETIQUETA_INICIOSESION_USUARIOINCORRECTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to te ha invitado a su sala. ¿Deseas unirte?.
        /// </summary>
        public static string ETIQUETA_INVITACIONSALA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_INVITACIONSALA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitación a sala.
        /// </summary>
        public static string ETIQUETA_INVITACIONSALA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_INVITACIONSALA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La invitación de sala se ha enviado correctamente.
        /// </summary>
        public static string ETIQUETA_INVITACIONSALAENVIADA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_INVITACIONSALAENVIADA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invitación a sala enviada.
        /// </summary>
        public static string ETIQUETA_INVITACIONSALAENVIADA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_INVITACIONSALAENVIADA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to se ha unido a la sala!.
        /// </summary>
        public static string ETIQUETA_MENSAJESALA_BIENVENIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_MENSAJESALA_BIENVENIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ha abandonado la sala!.
        /// </summary>
        public static string ETIQUETA_MENSAJESALA_DESPEDIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_MENSAJESALA_DESPEDIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string ETIQUETA_MENUPRINCIPAL_CERRARSESION {
            get {
                return ResourceManager.GetString("ETIQUETA_MENUPRINCIPAL_CERRARSESION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        public static string ETIQUETA_MENUPRINCIPAL_PERFIL {
            get {
                return ResourceManager.GetString("ETIQUETA_MENUPRINCIPAL_PERFIL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico inválido.
        /// </summary>
        public static string ETIQUETA_OPCIONESSALA_CORREOINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_OPCIONESSALA_CORREOINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dificultad.
        /// </summary>
        public static string ETIQUETA_OPCIONESSALA_DIFICULTAD {
            get {
                return ResourceManager.GetString("ETIQUETA_OPCIONESSALA_DIFICULTAD", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string ETIQUETA_OPCIONESSALA_DURACION {
            get {
                return ResourceManager.GetString("ETIQUETA_OPCIONESSALA_DURACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para invitar a un jugador que no esta en tu lista de amigos, es necesario que ingreses su correo electrónico para que le podamos enviar el código de sala.
        /// </summary>
        public static string ETIQUETA_OPCIONESSALA_INSTRUCCIONINVITACIONCORREO {
            get {
                return ResourceManager.GetString("ETIQUETA_OPCIONESSALA_INSTRUCCIONINVITACIONCORREO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fin del juego.
        /// </summary>
        public static string ETIQUETA_PARTIDA_JUEGOFINALIZADO {
            get {
                return ResourceManager.GetString("ETIQUETA_PARTIDA_JUEGOFINALIZADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo restante.
        /// </summary>
        public static string ETIQUETA_PARTIDA_TIEMPORESTANTE {
            get {
                return ResourceManager.GetString("ETIQUETA_PARTIDA_TIEMPORESTANTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No es posible unirse a la sala debido a que hay una partida en progreso. Por favor, inténtelo más tarde..
        /// </summary>
        public static string ETIQUETA_PARTIDAENCURSO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_PARTIDAENCURSO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Partida en transcurso.
        /// </summary>
        public static string ETIQUETA_PARTIDAENCURSO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_PARTIDAENCURSO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico no registrado.
        /// </summary>
        public static string ETIQUETA_RECUPERACION_CORREONOENCONTRADO {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACION_CORREONOENCONTRADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ingresa el correo electrónico con el cual te registraste, te enviaremos un código para que puedas restablecer tu contraseña.
        /// </summary>
        public static string ETIQUETA_RECUPERACION_INSTRUCCIONRECUPERACION {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACION_INSTRUCCIONRECUPERACION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Introduce el código.
        /// </summary>
        public static string ETIQUETA_RECUPERACION_INTRODUCECODIGO {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACION_INTRODUCECODIGO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tu código de restablecimiento es:.
        /// </summary>
        public static string ETIQUETA_RECUPERACION_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACION_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recuperación de contraseña.
        /// </summary>
        public static string ETIQUETA_RECUPERACION_RECUPERACIONCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACION_RECUPERACIONCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Correo inexistente.
        /// </summary>
        public static string ETIQUETA_RECUPERACIONCONTRASENA_CORREOINEXISTENTE {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACIONCONTRASENA_CORREOINEXISTENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El correo ingresado no existe.
        /// </summary>
        public static string ETIQUETA_RECUPERACIONCONTRASENA_MENSAJECORREOINEXISTENE {
            get {
                return ResourceManager.GetString("ETIQUETA_RECUPERACIONCONTRASENA_MENSAJECORREOINEXISTENE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ETIQUETA_REGISTRO_CONFIRMACIONCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTRO_CONFIRMACIONCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contraseña inválida.
        /// </summary>
        public static string ETIQUETA_REGISTRO_CONTRASENAINVALIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTRO_CONTRASENAINVALIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico no disponible.
        /// </summary>
        public static string ETIQUETA_REGISTRO_CORREONODISPONIBLE {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTRO_CORREONODISPONIBLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registro de jugador.
        /// </summary>
        public static string ETIQUETA_REGISTRO_REGISTROJUGADOR {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTRO_REGISTROJUGADOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seleccionar avatar.
        /// </summary>
        public static string ETIQUETA_REGISTRO_SELECCIONAVATAR {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTRO_SELECCIONAVATAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se ha realizado el registro correctamente. Ya puedes iniciar sesión en tu cuenta..
        /// </summary>
        public static string ETIQUETA_REGISTROREALIZADO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTROREALIZADO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registro de jugador realizado.
        /// </summary>
        public static string ETIQUETA_REGISTROREALIZADO_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_REGISTROREALIZADO_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña no restablecida.
        /// </summary>
        public static string ETIQUETA_RESTABLECIMIENTO_CONTRASENANORESTABLECIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_RESTABLECIMIENTO_CONTRASENANORESTABLECIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña restablecida.
        /// </summary>
        public static string ETIQUETA_RESTABLECIMIENTO_CONTRASENARESTABLECIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_RESTABLECIMIENTO_CONTRASENARESTABLECIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Su nueva contraseña ha sido actualizado correctamente.
        /// </summary>
        public static string ETIQUETA_RESTABLECIMIENTO_MENSAJECONTRASENAACTUALIZADA {
            get {
                return ResourceManager.GetString("ETIQUETA_RESTABLECIMIENTO_MENSAJECONTRASENAACTUALIZADA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Su contraseña no se pudo restablecer.
        /// </summary>
        public static string ETIQUETA_RESTABLECIMIENTO_MENSAJECONTRASENANORESTABLECIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_RESTABLECIMIENTO_MENSAJECONTRASENANORESTABLECIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string ETIQUETA_RESTABLECIMIENTO_RESTABLECIMIENTOCONTRASENA {
            get {
                return ResourceManager.GetString("ETIQUETA_RESTABLECIMIENTO_RESTABLECIMIENTOCONTRASENA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ha ganado la partida.
        /// </summary>
        public static string ETIQUETA_RESULTADOS_MENSAJEGANADOR {
            get {
                return ResourceManager.GetString("ETIQUETA_RESULTADOS_MENSAJEGANADOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string ETIQUETA_RESULTADOS_RESULTADOS {
            get {
                return ResourceManager.GetString("ETIQUETA_RESULTADOS_RESULTADOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Anfitrión.
        /// </summary>
        public static string ETIQUETA_SALA_ANFITRION {
            get {
                return ResourceManager.GetString("ETIQUETA_SALA_ANFITRION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string ETIQUETA_SALA_COPIAR {
            get {
                return ResourceManager.GetString("ETIQUETA_SALA_COPIAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mensajes.
        /// </summary>
        public static string ETIQUETA_SALA_MENSAJES {
            get {
                return ResourceManager.GetString("ETIQUETA_SALA_MENSAJES", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No es posible unirse a la sala debido a que se encuentra llena. Por favor, inténtelo más tarde..
        /// </summary>
        public static string ETIQUETA_SALALLENA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_SALALLENA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sala llena.
        /// </summary>
        public static string ETIQUETA_SALALLENA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_SALALLENA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to La solicitud de amistad se ha enviado correctamente.
        /// </summary>
        public static string ETIQUETA_SOLICITUDAMISTADENVIADA_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_SOLICITUDAMISTADENVIADA_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Solicitud de amistad enviada.
        /// </summary>
        public static string ETIQUETA_SOLICITUDAMISTADENVIADA_TITULO {
            get {
                return ResourceManager.GetString("ETIQUETA_SOLICITUDAMISTADENVIADA_TITULO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Código de sala inválido.
        /// </summary>
        public static string ETIQUETA_UNIRSESALA_CODIGOSALAINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_UNIRSESALA_CODIGOSALAINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Si cuentas con un código de acceso a una sala, puedes ingresarlo a continuación para poder unirte.
        /// </summary>
        public static string ETIQUETA_UNIRSESALA_INSTRUCCIONUNIRSE {
            get {
                return ResourceManager.GetString("ETIQUETA_UNIRSESALA_INSTRUCCIONUNIRSE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unirse a sala.
        /// </summary>
        public static string ETIQUETA_UNIRSESALA_UNIRSESALA {
            get {
                return ResourceManager.GetString("ETIQUETA_UNIRSESALA_UNIRSESALA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Campos excedidos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CAMPOSEXCEDIDOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CAMPOSEXCEDIDOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Campos inválidos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CAMPOSINVALIDOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CAMPOSINVALIDOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CAMPOSVACIOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CAMPOSVACIOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas diferentes.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CONTRASENADIFERENTE {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CONTRASENADIFERENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada excede la longitud máxima.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CONTRASENAEXCEDIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CONTRASENAEXCEDIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña inválida.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CONTRASENAINVALIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CONTRASENAINVALIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico inválido.
        /// </summary>
        public static string ETIQUETA_VALIDACION_CORREOINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_CORREOINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Longitud excedida.
        /// </summary>
        public static string ETIQUETA_VALIDACION_LONGITUDEXCEDIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_LONGITUDEXCEDIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Corrige los campos excedidos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECAMPOSEXCEDIDOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECAMPOSEXCEDIDOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Existen campos inválidos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECAMPOSINVALIDOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECAMPOSINVALIDOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No puedes dejar campos vacíos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECAMPOSVACIOS {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECAMPOSVACIOS", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECONTRASENADIFERENTE {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECONTRASENADIFERENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña que has ingresado es inválida.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECONTRASENAINVALIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECONTRASENAINVALIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La nueva contraseña que has ingresado es inválida.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECONTRASENANUEVA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECONTRASENANUEVA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico que has ingresado es inválido.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJECORREOINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJECORREOINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Corrige los campos excedidos.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJELONGITUDEXCEDIDA {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJELONGITUDEXCEDIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario que has ingresado es inválido.
        /// </summary>
        public static string ETIQUETA_VALIDACION_MENSAJENOMBREUSUARIOINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_MENSAJENOMBREUSUARIOINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario inválido.
        /// </summary>
        public static string ETIQUETA_VALIDACION_NOMBREUSUARIOINVALIDO {
            get {
                return ResourceManager.GetString("ETIQUETA_VALIDACION_NOMBREUSUARIOINVALIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código de verificación para concluir registro.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_ASUNTO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_ASUNTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código incorrecto.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_CODIGOINCORRECTO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_CODIGOINCORRECTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar registro.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_ERRORREGISTRO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_ERRORREGISTRO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tu código de verificación es:.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_MENSAJE {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_MENSAJE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificacion es incorrecto.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_MENSAJECODIGOINCORRECTO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_MENSAJECODIGOINCORRECTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El registro de usuario no se ha realizado.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_MENSAJEREGISTRONOREALIZADO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_MENSAJEREGISTRONOREALIZADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El registro de usuario se ha realizado correctamente.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_MENSAJEUSUARIOREGISTRADO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_MENSAJEUSUARIOREGISTRADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Registro realizado correctamente.
        /// </summary>
        public static string ETIQUETA_VERIFICACIONCORREO_REGISTROREALIZADO {
            get {
                return ResourceManager.GetString("ETIQUETA_VERIFICACIONCORREO_REGISTROREALIZADO", resourceCulture);
            }
        }
    }
}
