//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RompecabezasFei.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RompecabezasFei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activada.
        /// </summary>
        public static string Activada {
            get {
                return ResourceManager.GetString("Activada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Ajustes {
            get {
                return ResourceManager.GetString("Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ConfirmarContraseña {
            get {
                return ResourceManager.GetString("ConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña inválida.
        /// </summary>
        public static string ContraseñaInválida {
            get {
                return ResourceManager.GetString("ContraseñaInválida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo no disponible.
        /// </summary>
        public static string CorreoNoDisponible {
            get {
                return ResourceManager.GetString("CorreoNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nueva sala.
        /// </summary>
        public static string CrearNuevaSala {
            get {
                return ResourceManager.GetString("CrearNuevaSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desactivada.
        /// </summary>
        public static string Desactivada {
            get {
                return ResourceManager.GetString("Desactivada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe ser de al menos 8 caracteres, debes incluir letras mayúsculas, minúsculas y números.
        /// </summary>
        public static string InformacionRequisitosContraseña {
            get {
                return ResourceManager.GetString("InformacionRequisitosContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string Inglés {
            get {
                return ResourceManager.GetString("Inglés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string MiPerfil {
            get {
                return ResourceManager.GetString("MiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis amigos.
        /// </summary>
        public static string MisAmigos {
            get {
                return ResourceManager.GetString("MisAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo invitado.
        /// </summary>
        public static string ModoInvitado {
            get {
                return ResourceManager.GetString("ModoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Música.
        /// </summary>
        public static string Música {
            get {
                return ResourceManager.GetString("Música", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string NombreUsuario {
            get {
                return ResourceManager.GetString("NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string OpcionContraseñaOlvidada {
            get {
                return ResourceManager.GetString("OpcionContraseñaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta? Registrate aquí.
        /// </summary>
        public static string OpcionRegistrateAqui {
            get {
                return ResourceManager.GetString("OpcionRegistrateAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de usuario.
        /// </summary>
        public static string RegistroUsuario {
            get {
                return ResourceManager.GetString("RegistroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rompecabezas FEI.
        /// </summary>
        public static string RompecabezasFEI {
            get {
                return ResourceManager.GetString("RompecabezasFEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar avatar.
        /// </summary>
        public static string SeleccionarAvatar {
            get {
                return ResourceManager.GetString("SeleccionarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string TituloIniciarSesion {
            get {
                return ResourceManager.GetString("TituloIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string UnirseSala {
            get {
                return ResourceManager.GetString("UnirseSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario existente.
        /// </summary>
        public static string UsuarioExistente {
            get {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario incorrecto.
        /// </summary>
        public static string UsuarioIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioIncorrecto", resourceCulture);
            }
        }
    }
}
